const STATES = {
    NONE: 'NONE',
    WAITING_FOR_ID: 'WAITING_FOR_ID',
    WAITING_FOR_NAME: 'WAITING_FOR_NAME',
    WAITING_FOR_PRICE: 'WAITING_FOR_PRICE',
    WAITING_FOR_OLDPRICE: 'WAITING_FOR_OLDPRICE',
    WAITING_FOR_CREDIT: 'WAITING_FOR_CREDIT',
    WAITING_FOR_PRICEGRAPH: 'WAITING_FOR_PRICEGRAPH',
    WAITING_FOR_DELIVERY_TERM: 'WAITING_FOR_DELIVERY_TERM',
    WAITING_FOR_CATEGORIES_WAY: 'WAITING_FOR_CATEGORIES_WAY',
    WAITING_FOR_IMAGES: 'WAITING_FOR_IMAGES',
    WAITING_FOR_PARAM_TITLE: 'WAITING_FOR_PARAM_TITLE',
    WAITING_FOR_PARAM_VALUES: 'WAITING_FOR_PARAM_VALUES',
    WAITING_FOR_CHARACTERISTIC_TITLE: 'WAITING_FOR_CHARACTERISTIC_TITLE',
    WAITING_FOR_CHARACTERISTIC_KEY_VALUE: 'WAITING_FOR_CHARACTERISTIC_KEY_VALUE',
    CHARACTERISTIC_CONFIRMATION: 'CHARACTERISTIC_CONFIRMATION',
    ADD_MORE_OR_CONTINUE: 'ADD_MORE_OR_CONTINUE',
    WAITING_FOR_DESCRIPTION: 'WAITING_FOR_DESCRIPTION',
    WAITING_FOR_STORE_NAME: 'WAITING_FOR_STORE_NAME',
    WAITING_FOR_STORE_LOGO: 'WAITING_FOR_STORE_LOGO',
    WAITING_FOR_COMMON_INFO: 'WAITING_FOR_COMMON_INFO',
    CONFIRMATION: 'CONFIRMATION'
};

module.exports = {STATES };
